(TeX-add-style-hook "_region_"
 (lambda ()
    (TeX-run-style-hooks
     "hyperref"
     "unicode"
     "parskip"
     "parfill"
     "titlesec"
     "sf"
     "bf"
     "mathptm"
     "minitoc"
     "longtable"
     "multicol"
     "caption"
     "array"
     "paralist"
     "geometry"
     "pslatex"
     "subfig"
     "color"
     "graphics"
     "amsfonts"
     "amssymb"
     "amsmath"
     "vietnam"
     "utf8"
     "latex2e"
     "bk12"
     "book"
     "pdftex"
     "twoside"
     "a4paper"
     "12pt")))

