(TeX-add-style-hook "book"
 (lambda ()
    (TeX-run-style-hooks
     "minitoc"
     "longtable"
     "caption"
     "array"
     "paralist"
     "subfig"
     "color"
     "graphics"
     "amsfonts"
     "amssymb"
     "amsmath"
     "footmisc"
     "bottom"
     "multicol"
     "graphicx"
     "makeidx"
     "vietnam"
     "utf8"
     "latex2e"
     "styles/svmono10"
     "styles/svmono"
     "envcountsame"
     "envcountchap"
     "ch3/chuong3")))

